version: '3.8'
services:
  book-store:
    image: node
    container_name: book-store-angular
    command: sh -c "npm start"
    build: .
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - '4200:4200'
volumes:
  node_modules:
